const articleData = {
  auxilios:{tag:'Innovación',tagClass:'innovation',title:'Programa Interno de Primeros Auxilios Básicos',lead:'Abbott Medical fortalece su capacidad de respuesta inicial ante emergencias.',body:'<p>La iniciativa, elaborada por <strong>Tatiana Arias</strong>, busca implementar un programa interno de capacitación para contar progresivamente con personal preparado en los diferentes turnos.</p><p>Entre sus beneficios están disminuir el tiempo de respuesta, fortalecer la cultura de seguridad y prevención, brindar mayor confianza a los colaboradores y reducir acciones inadecuadas por falta de conocimiento.</p><p><strong>Inversión aproximada indicada:</strong> ₡165.000.</p>',image:'assets/innov_auxilios_oct/page-1.png',pdf:'docs/innovacion-primeros-auxilios-octubre.pdf'},
  guantes:{tag:'EHS / Seguridad',tagClass:'ehs',title:'Uso correcto de guantes',lead:'Cada tarea tiene su guante: elija el correcto según el riesgo.',body:'<ul><li><strong>Anticorte gris:</strong> para superficies con filos, bordes, puntas y manejo de basura.</li><li><strong>Nitrilo azul corto:</strong> contacto con químicos en áreas comunes; no para baños.</li><li><strong>Guantes de color:</strong> uso exclusivo en baños para evitar contaminación cruzada.</li><li><strong>Nitrilo verde largo:</strong> limpieza profunda de baños, dilución de químicos de cuarto limpio y remoción de cera.</li></ul><p>El nitrilo puede combinarse con el guante anticorte. Revise siempre el estado de los guantes antes de usarlos.</p>',image:'assets/guantes_oct/page-1.png',pdf:'docs/uso-correcto-guantes-octubre.pdf'},
  estadisticas:{tag:'EHS / Seguridad',tagClass:'ehs',title:'Reporte de eventos – Septiembre 2026',lead:'74 días sin accidentes registrables y 13 eventos reportados.',body:'<ul><li><strong>8</strong> eventos relacionados con el trabajo.</li><li><strong>5</strong> eventos no relacionados con el trabajo.</li><li><strong>Total:</strong> 13 eventos.</li></ul><p>Datos tomados de 4INSITE al 30 de septiembre de 2026.</p>',image:'assets/ehs_stats_oct/page-1.png',pdf:'docs/estadisticas-ehs-octubre.pdf'},
  documentacion:{tag:'Comunicado',tagClass:'recognition',title:'Documente correctamente sus tareas de limpieza',lead:'La documentación debe reflejar el trabajo realmente ejecutado.',body:'<p>Verifique la versión del formulario, busque un lugar tranquilo, mantenga el enfoque y utilice una superficie plana y horizontal.</p><ul><li>Documente las tareas al finalizarlas.</li><li>No rellene documentación sin haber ejecutado las tareas.</li><li>No firme con fechas anteriores ni por otra persona.</li><li>No falsifique información ni llene registros para otros.</li><li>Cuide la documentación controlada.</li></ul>',image:'assets/documentacion_oct/page-1.png',pdf:'docs/documentacion-operativa-octubre.pdf'},
  cancer:{tag:'Nuestra Gente',tagClass:'recognition',title:'Día Mundial contra el Cáncer de Mama',lead:'19 de octubre: unámonos en la lucha; la detección temprana puede salvar vidas.',body:'<p>SBM se suma al mensaje de concientización sobre la importancia de la detección temprana del cáncer de mama.</p>',image:'assets/rh_oct/page-1.png',pdf:'docs/recursos-humanos-octubre.pdf'},
  independencia:{tag:'Nuestra Gente',tagClass:'recognition',title:'SBM celebra 205 años de la Independencia de Costa Rica',lead:'Compartimos momentos de celebración en diferentes proyectos.',body:'<p>La edición reúne fotografías de <strong>Abbott Vascular, Oficinas Centrales, Cardinal, Creganna SR, Coloplast y Equifax M</strong> con motivo de la celebración de la Independencia de Costa Rica.</p>',image:'assets/rh_oct/page-2.png',pdf:'docs/recursos-humanos-octubre.pdf'},
  cuota:{tag:'Recursos Humanos',tagClass:'recognition',title:'Actualice su información del Plan Cuota Fúnebre',lead:'Un recordatorio para mantener al día la información de las personas incluidas en el plan.',body:'<p>El plan es voluntario y aplica únicamente para las personas anotadas en el formulario. Cada funcionario debe conservar una copia del formulario enviado.</p><p>Se recomienda actualizar la información ante el nacimiento de un hijo, cambio de pareja o matrimonio.</p>',image:'assets/rh_oct/page-3.png',pdf:'docs/recursos-humanos-octubre.pdf'},
  slogans:{tag:'Nuestra Gente',tagClass:'recognition',title:'Mi slogan para SBM',lead:'Dos colaboradores comparten en esta edición lo que SBM representa para ellos.',body:'<p><strong>Jasmina Flores – Smith+Nephew:</strong> destaca trabajar unidos con respeto, responsabilidad, colaboración y actitud positiva para contribuir a la satisfacción de los clientes.</p><p><strong>Brayan Arce – SHOCKWAVE:</strong> “Donde hay CALIDAD NO hay competencia, SBM CALIDAD que marca la diferencia.”</p>',image:'assets/slogan_brayan_oct/page-1.png',pdf:'docs/slogan-brayan-arce-octubre.pdf'},
  retenedores:{tag:'Innovación',tagClass:'innovation',title:'Retenedores para puertas',lead:'Una mejora sencilla para ingresar con carritos con mayor seguridad y cuidar la infraestructura.',body:'<p><strong>Elaborado por:</strong> Stwar Ortiz e Ignacio Sequeira, Edwards Lifesciences.</p><p>El personal podía golpear las puertas al ingresar con carritos hoteleros. La solución fue incorporar retenedores para mantener las puertas abiertas y facilitar el ingreso.</p><p><strong>Beneficios:</strong> mayor seguridad y protección de la infraestructura para evitar daños y quejas del cliente.</p>',image:'assets/innov_retenedores_oct/page-1.png',pdf:'docs/innovacion-retenedores-puertas-octubre.pdf'},
  recipientes:{tag:'Innovación',tagClass:'innovation',title:'Recipientes para removedor y cera',lead:'Mejor almacenamiento, ergonomía y transporte de productos químicos.',body:'<p><strong>Elaborado por:</strong> Stwar Ortiz, Edwards Lifesciences.</p><p>Las cajas Envirobox podían resultar incómodas al diluir el químico y generar riesgo de derrames. Se incorporaron recipientes de 10 litros para facilitar almacenamiento y transporte y evitar levantar cajas de 18,9 litros.</p><p><strong>Beneficios:</strong> seguridad de almacenaje, mejor postura al diluir y facilidad de transporte.</p>',image:'assets/innov_recipientes_oct/page-1.png',pdf:'docs/innovacion-recipientes-quimicos-octubre.pdf'},
  innovacion:{tag:'Innovación',tagClass:'innovation',title:'Tres ideas nacidas en la operación',lead:'Octubre reúne iniciativas de Edwards Lifesciences y Abbott Medical.',body:'<p>La edición presenta retenedores para puertas, recipientes de 10 litros para removedor y cera, y un Programa Interno de Primeros Auxilios Básicos.</p>',image:'assets/innov_auxilios_oct/page-1.png',pdf:'docs/innovacion-primeros-auxilios-octubre.pdf'}
};
let currentView='portada',previousView='portada';
const views=document.querySelectorAll('.view'),navLinks=document.querySelectorAll('.nav-link'),mobileMenu=document.getElementById('mobileMenu'),menuBtn=document.getElementById('menuBtn');
function showView(name,updateHash=true){const target=document.getElementById(`view-${name}`);if(!target)return;if(name!=='articulo')previousView=currentView==='articulo'?previousView:currentView;currentView=name;views.forEach(v=>v.classList.toggle('active',v===target));target.scrollTop=0;navLinks.forEach(b=>b.classList.toggle('active',b.dataset.view===name));mobileMenu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');if(updateHash)history.replaceState(null,'',`#${name}`)}
navLinks.forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));menuBtn.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('.article-link').forEach(card=>{const open=()=>openArticle(card.dataset.article);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})});
function openArticle(key){const data=articleData[key];if(!data)return;previousView=currentView;const tag=document.getElementById('articleTag');tag.textContent=data.tag;tag.className=`tag ${data.tagClass}`;document.getElementById('articleTitle').textContent=data.title;document.getElementById('articleLead').textContent=data.lead;document.getElementById('articleBody').innerHTML=data.body;document.getElementById('articleImage').src=data.image;document.getElementById('articleImage').alt=data.title;document.getElementById('articlePdf').href=data.pdf;document.getElementById('fullImageBtn').dataset.image=data.image;showView('articulo')}
document.getElementById('backBtn').addEventListener('click',()=>showView(previousView||'destacados'));const viewer=document.getElementById('viewer'),viewerImage=document.getElementById('viewerImage');document.getElementById('fullImageBtn').addEventListener('click',e=>{viewerImage.src=e.currentTarget.dataset.image;viewer.showModal()});document.getElementById('closeViewer').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&currentView==='articulo'&&!viewer.open)showView(previousView||'destacados')});const initial=location.hash.replace('#','');showView(document.getElementById(`view-${initial}`)?initial:'portada',false);
